package-lock.json
package.json
src/app/(dashboard)/page.tsx
src/app/_components/sidebar-item.tsx
src/app/auth/login/_components/LoginPage.tsx
src/middleware.ts
src/utils/deleteCookie.ts
src/utils/logout.tsx

Add route protecting through middleware.ts file.

route protecting

---

src/app/editprofile/page.tsx
src/app/profile/page.tsx

Profile page according to wireframe updated

profile ui: wireframe

---

package-lock.json
src/app/auth/login/_components/LoginPage.tsx
src/middleware.ts
src/utils/logout.tsx

Encoded the user in cookies, admin route protecting and dynamically routing on basis of roleslist

Route-protecting for admin and dynamic redirection on basis of role, 

---

package-lock.json
src/app/student/courses/[viewcourses]/modules/[moduleID]/page.tsx
src/app/student/courses/[viewcourses]/page.tsx
src/app/student/courses/page.tsx

Getting and showing courses dynamically and also integration of post apis for assignments, articles and quizzes

Student courses/modules and progress apis integration

---

src/app/admin/courses/[courseId]/_components/batches.tsx

1.Now you dont have to reload everytime you enroll students

fix: reloading issue

---

src/middleware.ts

undefined issue for user logout student side

Feature student courses

---

src/app/_components/sidebar-routes.tsx

fix: Routes

---

src/app/auth/login/_components/LoginPage.tsx
src/app/student/explore/page.tsx

env file update and url for dev login added

login url changed using env

---

src/app/_components/datatable/data-table.tsx
src/app/admin/courses/[courseId]/(courseTabs)/students/page.tsx
src/app/admin/courses/[courseId]/_components/addStudentsmodal.tsx

1. Rows Per Page 
2. Some JIRA tasks

feature: Pagination Rows Per Page And Some Jira Tasks

---

src/app/_components/datatable/columns.tsx
src/app/admin/courses/[courseId]/_components/addStudentsmodal.tsx
src/app/admin/courses/[courseId]/_components/deleteModal.tsx
src/store/store.ts

Add students with same email error fixed
UI not updating without refresh fixed
Delete button issue fixed
Could not create batch without refreshing after adding student fixed

delete student issues, refresh issues, add student errors all fixed

---

src/app/_components/datatable/columns.tsx

FIx: attendence in students Data Table

---

src/app/_components/breadcrumbCmponent.tsx
src/app/admin/courses/[courseId]/(courseTabs)/batches/page.tsx
src/app/admin/courses/[courseId]/_components/addStudentsmodal.tsx
src/app/admin/courses/[courseId]/_components/deleteModal.tsx
src/app/admin/courses/[courseId]/batch/[batchId]/page.tsx
src/app/admin/courses/page.tsx
src/utils/students.ts

1. Search Implemented in every page in the admin Side
2. Delete Modal Input validation fixed
3. Error Message fIxed

feature: Searching and  Bug Fix

---

src/app/_components/datatable/data-table-column-header.tsx
src/app/admin/courses/[courseId]/(courseTabs)/batches/columns.tsx
src/components/ui/combobox.tsx

1. Change batch issue for students sorted.
2. Select multiple students option removed.
3. Sorting by Batch Assigned to added
4. Sort by profile picture removed

student data table changes and bug fixes

---

src/app/admin/courses/[courseId]/batch/[batchId]/columns.tsx

Changes for multiple selection sorted for batches data table
Changes for the profile picture sorting removed for batches data table

UI changes for batch data table

---

src/app/admin/courses/[courseId]/(courseTabs)/students/columns.tsx
src/app/admin/courses/[courseId]/(courseTabs)/submissions/[studentReport]/page.tsx
src/app/admin/courses/[courseId]/(courseTabs)/submissions/page.tsx
src/app/admin/courses/[courseId]/_components/AssesmentComponent.tsx
src/app/admin/courses/[courseId]/_components/Assesments.tsx
src/app/admin/courses/[courseId]/_components/IndividualStudent.tsx
src/app/admin/courses/[courseId]/_components/OverviewComponent.tsx
src/app/admin/courses/[courseId]/_components/PraticeProblems.tsx
src/app/admin/courses/[courseId]/_components/Projects.tsx
src/app/admin/courses/[courseId]/_components/individualStudentAssesment.tsx
src/app/admin/courses/[courseId]/_components/submissionComponent.tsx
src/components/ui/button.tsx
src/components/ui/combobox.tsx

Submission Page UI implemented

UI: submission Page

---

package-lock.json
src/app/admin/courses/[courseId]/(courseTabs)/students/columns.tsx
src/app/admin/courses/[courseId]/_components/deleteModal.tsx
src/app/admin/courses/[courseId]/batch/[batchId]/page.tsx

1. Delete Batch Issue
2. Batch Assigned Issue (Partially Solved)
3. Minor Bug Fixes

Fix: Bug Fixes

---

src/app/student/courses/[viewcourses]/[recordings]/_components/RecordingCard.tsx

meetingId issue temporary fix for main branch

meetingId issue temporary fix for main branch

---

src/app/admin/courses/[courseId]/_components/newClassDialog.tsx
src/app/admin/courses/[courseId]/module/_components/codingChallenge/CodingChallenge.tsx
src/app/admin/resource/_components/NewCodingProblemForm.tsx
src/app/admin/resource/coding/column.tsx
src/app/admin/resource/coding/page.tsx
src/store/store.ts
src/utils/admin.ts

Columns issue for delete functionality sorted
UI completed for Create Coding Question
UserId updated in the UI
on Delete refresh not needed and correct question delete now
Create sessions few variables type changed to Number as per requested by Prem

delete option sorted

---

src/app/admin/resource/_components/NewCodingProblemForm.tsx
src/app/admin/resource/_components/NewOpenEndedQuestionForm.tsx
src/app/admin/resource/open-ended/column.tsx
src/app/admin/resource/open-ended/page.tsx
src/store/store.ts
src/utils/admin.ts
src/utils/constant.ts
src/utils/data/schema.tsx

Entire Open-Ended Questions Creation Complete
Only Edit API remaining

entire Open-ended questions integration complete

---

src/app/admin/resource/_components/EditCodingQuestionForm.tsx
src/app/admin/resource/_components/EditOpenEndedQuestionForm.tsx
src/app/admin/resource/coding/column.tsx
src/app/admin/resource/coding/page.tsx
src/app/admin/resource/open-ended/column.tsx
src/app/admin/resource/open-ended/page.tsx
src/store/store.ts
src/utils/admin.ts

multiple test cases for creating coding questions fixed
edit apis for coding & open-ended questions integrated

multiple options and editing api

---

src/app/admin/courses/[courseId]/(courseTabs)/curriculum/page.tsx
src/app/admin/courses/[courseId]/_components/curricullumCard.tsx
src/app/admin/courses/[courseId]/module/[moduleId]/page.tsx
src/app/admin/courses/[courseId]/module/_components/Article/AddArticle.tsx

Create Project Module
Update projects
TipTap integration

project creation and editing apis with TipTap added

---

src/app/admin/courses/[courseId]/module/[moduleId]/page.tsx
src/app/admin/courses/[courseId]/module/_components/Article/AddArticle.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/AddAssessment.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/CodingQuestions.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/QuizQuestions.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/SelectCodingQuestions.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/SelectQuizQuestions.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/SelectedQuestions.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/SettingsAssessment.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/ToggleSwitch.tsx
src/utils/admin.ts

Entire Assessment Complete code pushed
Article data not coming issue sorted

Entire Assessment Complete

---

src/app/admin/courses/[courseId]/module/[moduleId]/page.tsx
src/app/admin/courses/[courseId]/module/_components/Article/AddArticle.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/AddAssessment.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/SettingsAssessment.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/ToggleSwitch.tsx

Fixed issues for create assessment

fixed created assessment issues

---

src/app/admin/courses/[courseId]/module/[moduleId]/page.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/AddAssessment.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/SettingsAssessment.tsx
src/app/admin/courses/[courseId]/module/_components/Assessment/ToggleSwitch.tsx
src/app/admin/courses/[courseId]/module/_components/ChapterItem.tsx
src/app/admin/resource/_components/EditOpenEndedQuestionForm.tsx
src/app/admin/resource/_components/NewOpenEndedQuestionForm.tsx
src/app/admin/resource/coding/column.tsx
src/utils/data/schema.tsx

Marks field taking in negative numbers - fixed
settings toggle switch not working - fixed
integration of usage api for coding questions - done
title not updating for assessments - fixed
change icons for assessments - done

bug fixes for create assessment and other bug fixes and UI

---

src/app/admin/courses/[courseId]/(courseTabs)/sessions/CreateSession.tsx
src/app/admin/courses/[courseId]/(courseTabs)/sessions/page.tsx
src/app/admin/courses/[courseId]/_components/SubmissionCard.tsx
src/app/admin/courses/[courseId]/_components/newClassDialog.tsx
src/app/admin/courses/[courseId]/_components/submissionComponent.tsx
src/app/admin/courses/[courseId]/module/_components/quiz/Quiz.tsx
src/app/admin/courses/[courseId]/submissionProblems/[StudentProblemData]/columns.tsx
src/app/admin/courses/[courseId]/submissionProblems/[StudentProblemData]/page.tsx
src/app/student/_components/schedule.tsx
src/app/student/courses/[viewcourses]/batch/[batchId]/page.tsx
src/app/student/courses/[viewcourses]/modules/[moduleID]/page.tsx
src/app/student/courses/[viewcourses]/modules/_components/Quiz.tsx
src/app/student/courses/[viewcourses]/page.tsx
src/app/student/courses/page.tsx
src/app/student/recordings/page.tsx
src/lib/utils.ts
src/store/store.ts
src/utils/data/schema.tsx

1. Pagination Added inside Session Page

Pagination and Searching for Session Page

---

src/app/student/_components/schedule.tsx

Changes brief -
1. Add dropdown for multiple courses
2. Displayed selected course attendance

Add dropdown for multiple courses

---

src/app/admin/courses/[courseId]/(courseTabs)/sessions/CreateSession.tsx

fix create Session
